### ISSUE TITLE
Bad robot structure (only white body), on Ylo2 robot

### ISSUE THREAD

**Issue by elpimous** [robomechanics/quad-sdk#340]
Hi the team,
I have a good xacro model , (a modification of your A1_description)
working perfectly on rviz, and joints tested : 
![Capture d’écran de 2023-01-30 23-59-12](https://user-images.githubusercontent.com/8529940/215617102-a4827c7d-0e0c-49aa-83e0-a3c752c62a4d.png)
![Capture d’écran de 2023-01-31 00-01-06](https://user-images.githubusercontent.com/8529940/215617108-bd1b91ce-3339-485d-9f25-cde8c76b14b0.png)

**Comment by elpimous** [comment]
I used your command line to create urdf and sdf files : 
`rosrun xacro xacro --inorder -o /home/ylo2/catkin_ws/src/quad-sdk/quad_simulator/ylo2_description/urdf/ylo2.urdf /home/ylo2/catkin_ws/src/quad-sdk/quad_simulator/ylo2_description/xacro/robot.xacro DEBUG:=false`

and

`gz sdf -p /home/ylo2/catkin_ws/src/quad-sdk/quad_simulator/ylo2_description/urdf/ylo2.urdf > /home/ylo2/catkin_ws/src/quad-sdk/quad_simulator/ylo2_description/sdf_mesh/ylo2.sdf`

**Comment by elpimous** [comment]
I had an error on sdf file. this line was fault : I removed it !
![Capture d’écran de 2023-01-31 00-13-19](https://user-images.githubusercontent.com/8529940/215617823-135f937e-6d74-4f5e-b263-29c8a50deb9f.png)

when launching : `roslaunch quad_utils quad_gazebo.launch robot_type:=ylo2` I don't see any error on terminal.
![Capture d’écran de 2023-01-30 23-58-25](https://user-images.githubusercontent.com/8529940/215618065-a7ebf4b4-2a4e-4fff-b13d-a9525a914ada.png)
![Capture d’écran de 2023-01-30 23-58-30](https://user-images.githubusercontent.com/8529940/215618066-0302d272-ee52-4b4c-9117-3af9becac8a7.png)

**Comment by elpimous** [comment]
Any idea ??

**Comment by elpimous** [comment]
Well. SDF creation wasn't a success !!!
I corrected some things, starting from A1 original sdf file...
Now, working correctly.

![Capture d’écran de 2023-01-27 20-57-58](https://user-images.githubusercontent.com/8529940/215773354-ecd70791-9ec6-4ce7-a9da-aa2935a65dd1.png)
Hope it will help each other.

**Comment by DanielChaseButterfield** [comment]
@elpimous I'm having a very similar issue, I checked my sdf and urdf files, and they still don't work. You mentioned "I corrected some things, starting from A1 original sdf file..." Do you remember what you did?

Currently, I'm taking out the "ignition" line as you did earlier in this thread.

Also, I noticed that running `gz sdf` currently generates a sdf file with version=1.7 instead of 1.6 as before, so I wondered if that could be the cause. However, when I try to use `gz sdf` to generate a file with version=1.6, I get the following error:
```
Error [SDF.cc:459] Unable to find SDF filename[root.sdf] with version =1.7
Error [parser.cc:159] Could not find the 'element' element in the xml file
ERROR: SDF parsing the xml failed
```

**Comment by elpimous** [comment]
Hi Daniel.
Building SDF file from command Line don t work for me.
I had to use a default one, for ex A1, and adapt it with my one. (I did the SDF build command line, only to be able to extract needed values, for mt A1 adapted SDF file.
A long process, but working.
Hope it will help you
Vincent
